---
deployment:
  tasks:
    - export DEPLOYPATH=/home/f0i89r1ensbu/public_html/
    - /home/f0i89r1ensbu/repositories/LightSoilPot/cp index.html $DEPLOYPATH
    - /home/f0i89r1ensbu/repositories/LightSoilPot/cp favicon.png $DEPLOYPATH
    - /home/f0i89r1ensbu/repositories/LightSoilPot/cp libs $DEPLOYPATH