---
deployment:
  tasks:
    - export DEPLOYPATH=../../public_html/
    - cp ./index.html $DEPLOYPATH
    - cp ./favicon.png $DEPLOYPATH
    - cp ./libs/ $DEPLOYPATH
    - cp ./dist/ $DEPLOYPATH
    - npm run talk