
name: Deploy

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - run: rm -rf dist/
    - run: npm ci
    - run: npm run build --if-present
    - run: git add -A
    - run: git diff-index --quiet HEAD || git commit -m "XXX | task build"
    - run: git push
    - run: echo "finished"

